-- Beyond the Graph: The X-Y Files. Run once in Supabase SQL Editor.
create extension if not exists "pgcrypto";
create type public.app_role as enum ('admin','member','teacher','viewer');
create type public.topic_status as enum ('not_started','in_progress','completed');
create type public.post_status as enum ('draft','published');
create type public.media_type as enum ('image','video','youtube','google_drive');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text unique not null, name text not null, role app_role not null default 'viewer', avatar_url text, bio text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.topics (id uuid primary key default gen_random_uuid(), title text unique not null, slug text unique not null, description text, parent_id uuid references public.topics(id) on delete set null, status topic_status not null default 'not_started', order_index int not null default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.posts (id uuid primary key default gen_random_uuid(), author_id uuid not null references public.profiles(id) on delete cascade, caption text not null check(char_length(caption)<=3000), topic_id uuid references public.topics(id) on delete set null, status post_status not null default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table public.post_media (id uuid primary key default gen_random_uuid(), post_id uuid not null references public.posts(id) on delete cascade, media_type media_type not null, storage_path text, external_url text, thumbnail_url text, caption text, created_at timestamptz default now(), check(storage_path is not null or external_url is not null));
create table public.comments (id uuid primary key default gen_random_uuid(), post_id uuid not null references public.posts(id) on delete cascade, author_id uuid not null references public.profiles(id) on delete cascade, content text not null check(char_length(content)<=1500), created_at timestamptz default now(), updated_at timestamptz default now());
create table public.reactions (id uuid primary key default gen_random_uuid(), post_id uuid not null references public.posts(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, reaction_type text not null check(reaction_type in ('love','proud','helpful','funny','great_work')), created_at timestamptz default now(), unique(post_id,user_id,reaction_type));
create table public.outputs (id uuid primary key default gen_random_uuid(), title text not null, topic_id uuid references public.topics(id) on delete set null, description text, objective text, process text, final_output_url text, reflection jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.output_members (output_id uuid references public.outputs(id) on delete cascade, member_id uuid references public.profiles(id) on delete cascade, contribution text, created_at timestamptz default now(), primary key(output_id,member_id));
create table public.documentation (id uuid primary key default gen_random_uuid(), title text not null, description text, topic_id uuid references public.topics(id) on delete set null, activity text, date date, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.documentation_media (id uuid primary key default gen_random_uuid(), documentation_id uuid references public.documentation(id) on delete cascade, storage_path text not null, media_type media_type not null, caption text, created_at timestamptz default now());
create table public.videos (id uuid primary key default gen_random_uuid(), title text not null, description text, topic_id uuid references public.topics(id) on delete set null, video_type media_type not null, video_url text not null, thumbnail_url text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.peer_checkins (id uuid primary key default gen_random_uuid(), member_id uuid not null references public.profiles(id) on delete cascade, week_label text not null, mood text not null check(mood in ('doing_well','okay','struggling','need_help')), following_lessons text, difficult_topic text, group_improvement text, support_needed text, submitted_at timestamptz default now());
create table public.teacher_evaluations (id uuid primary key default gen_random_uuid(), teacher_id uuid not null references public.profiles(id), output_id uuid references public.outputs(id) on delete cascade, mathematical_accuracy numeric, creativity numeric, collaboration numeric, presentation numeric, documentation numeric, overall_score numeric, comments text, recommendations text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.portfolio_documents (id uuid primary key default gen_random_uuid(), pdf_storage_path text, pdf_filename text, canva_url text, qr_destination_url text, qr_image_url text, updated_at timestamptz default now());
create table if not exists public.teacher_comments (id uuid primary key default gen_random_uuid(), teacher_name text not null, comments text not null, recommendations text, created_at timestamptz default now());
create table if not exists public.shared_assets (id uuid primary key default gen_random_uuid(), title text not null, asset_type text not null, storage_path text not null, created_at timestamptz default now());
create table public.activity_log (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete set null, action_type text not null, entity_type text not null, entity_id uuid, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create index posts_topic_idx on public.posts(topic_id,created_at desc); create index comments_post_idx on public.comments(post_id,created_at); create index topics_parent_idx on public.topics(parent_id,order_index);

create or replace function public.is_admin_or_teacher() returns boolean language sql stable security definer as $$ select exists(select 1 from public.profiles where id=auth.uid() and role in ('admin','teacher')) $$;
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at(); create trigger topics_touch before update on public.topics for each row execute function public.touch_updated_at(); create trigger posts_touch before update on public.posts for each row execute function public.touch_updated_at();

alter table public.profiles enable row level security; alter table public.topics enable row level security; alter table public.posts enable row level security; alter table public.post_media enable row level security; alter table public.comments enable row level security; alter table public.reactions enable row level security; alter table public.outputs enable row level security; alter table public.output_members enable row level security; alter table public.documentation enable row level security; alter table public.documentation_media enable row level security; alter table public.videos enable row level security; alter table public.peer_checkins enable row level security; alter table public.teacher_evaluations enable row level security; alter table public.portfolio_documents enable row level security;
alter table public.teacher_comments enable row level security; alter table public.shared_assets enable row level security;
create policy "public read profiles" on public.profiles for select using(true); create policy "users update self" on public.profiles for update using(auth.uid()=id);
create policy "public read topics" on public.topics for select using(true); create policy "admins manage topics" on public.topics for all using(public.is_admin_or_teacher()) with check(public.is_admin_or_teacher());
create policy "read published posts" on public.posts for select using(status='published' or author_id=auth.uid() or public.is_admin_or_teacher()); create policy "members create own posts" on public.posts for insert with check(author_id=auth.uid()); create policy "owners manage posts" on public.posts for update using(author_id=auth.uid() or public.is_admin_or_teacher()); create policy "owners delete posts" on public.posts for delete using(author_id=auth.uid() or public.is_admin_or_teacher());
create policy "read post media" on public.post_media for select using(true); create policy "post owners manage media" on public.post_media for all using(exists(select 1 from public.posts p where p.id=post_id and (p.author_id=auth.uid() or public.is_admin_or_teacher()))) with check(exists(select 1 from public.posts p where p.id=post_id and (p.author_id=auth.uid() or public.is_admin_or_teacher())));
create policy "read comments" on public.comments for select using(true); create policy "write own comments" on public.comments for insert with check(author_id=auth.uid()); create policy "manage own comments" on public.comments for update using(author_id=auth.uid() or public.is_admin_or_teacher());
create policy "read reactions" on public.reactions for select using(true); create policy "write own reactions" on public.reactions for insert with check(user_id=auth.uid()); create policy "remove own reactions" on public.reactions for delete using(user_id=auth.uid() or public.is_admin_or_teacher());
create policy "public read outputs" on public.outputs for select using(true); create policy "staff manage outputs" on public.outputs for all using(public.is_admin_or_teacher()) with check(public.is_admin_or_teacher()); create policy "public read output members" on public.output_members for select using(true); create policy "staff manage output members" on public.output_members for all using(public.is_admin_or_teacher()) with check(public.is_admin_or_teacher());
create policy "public read documentation" on public.documentation for select using(true); create policy "staff manage documentation" on public.documentation for all using(public.is_admin_or_teacher()) with check(public.is_admin_or_teacher()); create policy "public read documentation media" on public.documentation_media for select using(true); create policy "staff manage documentation media" on public.documentation_media for all using(public.is_admin_or_teacher()) with check(public.is_admin_or_teacher()); create policy "public read videos" on public.videos for select using(true); create policy "staff manage videos" on public.videos for all using(public.is_admin_or_teacher()) with check(public.is_admin_or_teacher());
create policy "self read checkins" on public.peer_checkins for select using(member_id=auth.uid() or public.is_admin_or_teacher()); create policy "self submit checkins" on public.peer_checkins for insert with check(member_id=auth.uid()); create policy "staff read evaluations" on public.teacher_evaluations for select using(public.is_admin_or_teacher()); create policy "teachers write evaluations" on public.teacher_evaluations for insert with check(public.is_admin_or_teacher()); create policy "public read portfolio docs" on public.portfolio_documents for select using(true); create policy "admins manage portfolio docs" on public.portfolio_documents for all using(public.is_admin_or_teacher()) with check(public.is_admin_or_teacher());
create policy "public read teacher comments" on public.teacher_comments for select using(true); create policy "staff manage teacher comments" on public.teacher_comments for all using(public.is_admin_or_teacher()) with check(public.is_admin_or_teacher()); create policy "public read shared assets" on public.shared_assets for select using(true); create policy "staff manage shared assets" on public.shared_assets for all using(public.is_admin_or_teacher()) with check(public.is_admin_or_teacher());

-- Storage buckets; set policies per desired public/private access before uploads.
insert into storage.buckets (id,name,public) values ('avatars','avatars',true),('post-media','post-media',false),('documentation','documentation',false),('videos','videos',false),('outputs','outputs',false),('portfolio-documents','portfolio-documents',false) on conflict do nothing;

-- Seed only known members and topics after their auth users exist. Topic seed is safe now.
insert into public.topics(title,slug,status,order_index) values ('Conic Sections','conic-sections','not_started',1),('Sequences & Series','sequences-series','not_started',6),('Induction','induction','not_started',7),('Combination','combination','not_started',8) on conflict(slug) do nothing;
insert into public.topics(title,slug,parent_id,status,order_index) select v.title,v.slug,p.id,'not_started',v.ord from (values ('Circles','circles',2),('Parabolas','parabolas',3),('Ellipses','ellipses',4),('Hyperbolas','hyperbolas',5)) as v(title,slug,ord) cross join public.topics p where p.slug='conic-sections' on conflict(slug) do nothing;
