import {NextRequest,NextResponse} from 'next/server';
import {supabaseAdmin} from '@/lib/supabase/admin';

const allowed=new Set(['image/','video/','audio/']);
function safeName(value:string){return value.replace(/[^a-zA-Z0-9._-]/g,'-');}
function kind(file:File){return file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':'audio';}
async function signed(db:NonNullable<ReturnType<typeof supabaseAdmin>>,path:string|null){if(!path)return null;const {data}=await db.storage.from('post-media').createSignedUrl(path,60*60);return data?.signedUrl??null;}
export async function GET(){const db=supabaseAdmin();if(!db)return NextResponse.json({posts:[]});const {data}=await db.from('journal_entries').select('id,author_name,caption,topic_slug,created_at,journal_media(id,media_kind,storage_path,external_url,filename)').order('created_at',{ascending:false});const posts=await Promise.all((data??[]).map(async entry=>({...entry,journal_media:await Promise.all((entry.journal_media??[]).map(async(media:{storage_path:string|null})=>({...media,view_url:await signed(db,media.storage_path)})))})));return NextResponse.json({posts});}
export async function POST(request:NextRequest){if(!request.cookies.get('xy_portfolio_access'))return NextResponse.json({error:'Sign in first.'},{status:401});const db=supabaseAdmin();if(!db)return NextResponse.json({error:'Posting media needs SUPABASE_SERVICE_ROLE_KEY in Vercel first.'},{status:503});try{const form=await request.formData(),caption=String(form.get('caption')||'').trim(),author=String(form.get('author_name')||'').trim(),topic=String(form.get('topic_slug')||'').trim()||null,music=String(form.get('music_url')||'').trim(),files=form.getAll('files').filter((item):item is File=>item instanceof File&&item.size>0);if(!caption)return NextResponse.json({error:'Write a caption first.'},{status:400});if(!author)return NextResponse.json({error:'Add your name first.'},{status:400});if(files.length>6)return NextResponse.json({error:'Attach up to six files per post.'},{status:400});if(files.some(file=>!allowed.has(file.type.slice(0,file.type.indexOf('/')+1))))return NextResponse.json({error:'Use image, video, or audio files only.'},{status:400});const {data:entry,error:entryError}=await db.from('journal_entries').insert({author_name:author,caption,topic_slug:topic}).select().single();if(entryError)throw entryError;const media=[] as {entry_id:string;media_kind:string;storage_path?:string;external_url?:string;filename?:string}[];for(const file of files){const path=`journal/${entry.id}/${Date.now()}-${safeName(file.name)}`;const {error}=await db.storage.from('post-media').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;media.push({entry_id:entry.id,media_kind:kind(file),storage_path:path,filename:file.name});}if(music){try{new URL(music);}catch{return NextResponse.json({error:'Use a valid music link.'},{status:400});}media.push({entry_id:entry.id,media_kind:'music_link',external_url:music,filename:'Music link'});}if(media.length){const {error}=await db.from('journal_media').insert(media);if(error)throw error;}return NextResponse.json({entry});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to publish this post.'},{status:500});}}
