import {NextRequest,NextResponse} from 'next/server';
import {supabaseAdmin} from '@/lib/supabase/admin';
const valid=new Set(['topic','member','media']);
function fileKind(file:File){return file.type==='application/pdf'?'pdf':file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':'file';}
function bucket(kind:string){return kind==='video'?'videos':'documentation';}
function clean(name:string){return name.replace(/[^a-zA-Z0-9._-]/g,'-');}
function validScope(type:string,key:string){return valid.has(type)&&Boolean(key.trim());}
export async function GET(request:NextRequest){const db=supabaseAdmin(),type=request.nextUrl.searchParams.get('type')||'',key=request.nextUrl.searchParams.get('key')||'';if(!db||!valid.has(type)||!key)return NextResponse.json({files:[]});const {data}=await db.from('folder_files').select('*').eq('folder_type',type).eq('folder_key',key).order('created_at',{ascending:false});const files=await Promise.all((data??[]).map(async file=>{const {data:signed}=await db.storage.from(file.storage_bucket).createSignedUrl(file.storage_path,3600);return {...file,view_url:signed?.signedUrl??null}}));return NextResponse.json({files});}
export async function POST(request:NextRequest){if(!request.cookies.get('xy_portfolio_access'))return NextResponse.json({error:'Sign in first.'},{status:401});const db=supabaseAdmin();if(!db)return NextResponse.json({error:'Uploads need SUPABASE_SERVICE_ROLE_KEY in Vercel first.'},{status:503});try{const contentType=request.headers.get('content-type')||'';
if(contentType.includes('application/json')){const body=await request.json(),action=String(body.action||''),type=String(body.type||''),key=String(body.key||''),title=String(body.title||'').trim(),filename=String(body.filename||''),mime=String(body.mime||'application/octet-stream');if(!validScope(type,key)||!filename)return NextResponse.json({error:'Choose a valid folder and file first.'},{status:400});const kind=mime==='application/pdf'?'pdf':mime.startsWith('image/')?'image':mime.startsWith('video/')?'video':'file',store=bucket(kind),path=`${type}/${key}/${Date.now()}-${clean(filename)}`;
if(action==='prepare'){const {data,error}=await db.storage.from(store).createSignedUploadUrl(path);if(error)throw error;return NextResponse.json({bucket:store,path,token:data.token,kind,title:title||filename});}
if(action==='complete'){const {data,error}=await db.from('folder_files').insert({folder_type:type,folder_key:key,title:title||filename,file_kind:kind,storage_bucket:store,storage_path:String(body.path||path)}).select().single();if(error)throw error;return NextResponse.json({file:data});}
return NextResponse.json({error:'Unknown upload action.'},{status:400});}
const form=await request.formData(),type=String(form.get('type')||''),key=String(form.get('key')||''),title=String(form.get('title')||'').trim(),file=form.get('file');if(!validScope(type,key)||!(file instanceof File)||!file.size)return NextResponse.json({error:'Choose a file first.'},{status:400});const kind=fileKind(file),store=bucket(kind),path=`${type}/${key}/${Date.now()}-${clean(file.name)}`,{error:uploadError}=await db.storage.from(store).upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {data,error}=await db.from('folder_files').insert({folder_type:type,folder_key:key,title:title||file.name,file_kind:kind,storage_bucket:store,storage_path:path}).select().single();if(error)throw error;return NextResponse.json({file:data});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to upload.'},{status:500});}}
